# Generated by Django 5.0.6 on 2024-07-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stureg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('surname', models.CharField(max_length=34)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=23)),
            ],
        ),
    ]
